allow faucet script to accept customized hopramount and nativeamount

diff --git a/packages/ethereum/contracts/Makefile b/packages/ethereum/contracts/Makefile
--- a/packages/ethereum/contracts/Makefile
+++ b/packages/ethereum/contracts/Makefile
@@ -75,16 +75,18 @@ endif
 	$(forge-script) script/SingleAction.s.sol:SingleActionFromPrivateKeyScript \
 		--broadcast --sig "mintXHopr(address,uint256)" $(recipient) 1000
 
-# E.g. make faucet environment-name=anvil-localhost environment-type=development recipient=0x2402da10A6172ED018AEEa22CA60EDe1F766655C
+# E.g. make faucet environment-name=anvil-localhost environment-type=development recipient=0x2402da10A6172ED018AEEa22CA60EDe1F766655C hopramount=10 nativeamount=1
+# E.g. make faucet environment-name=anvil-localhost environment-type=development recipient=0x2402da10A6172ED018AEEa22CA60EDe1F766655C nativeamount=1
+# E.g. make faucet environment-name=anvil-localhost environment-type=development recipient=0x2402da10A6172ED018AEEa22CA60EDe1F766655C hopramount=10
 .PHONY: faucet
 faucet: ensure-environment-is-set ensure-privatekey-is-set
-faucet: ## Mint 20000 HOPR tokens and send 10 native tokens to the recipient
+faucet: ## Mint some (default: 20000) HOPR tokens and send some (default value: 10) native tokens to the recipient hopramount
 ifeq ($(recipient),)
-	echo "parameter <recipient> missing" >&2 && exit 1
+    echo "parameter <recipient> missing" >&2 && exit 1
 endif
-	$(forge-script) script/SingleAction.s.sol:SingleActionFromPrivateKeyScript \
-		--broadcast --sig "mintHopr(address,uint256)" $(recipient) 20000
-	cast send $(recipient) --value 10ether --private-key $(PRIVATE_KEY)
+    $(forge-script) script/SingleAction.s.sol:SingleActionFromPrivateKeyScript \
+        --broadcast --sig "mintHoprAndSendNative(address,uint256,uint256)" \
+        $(recipient) $(or $(hopramount),20000) $(or $(nativeamount),10)
 
 # E.g. make request-nrnft environment-name=anvil-localhost environment-type=development recipient=0x2402da10A6172ED018AEEa22CA60EDe1F766655C nftrank=developer
 .PHONY: request-nrnft
