Fixing coderabbit suggestions

diff --git a/.github/workflows/build-dappnode.yaml b/.github/workflows/build-dappnode.yaml
--- a/.github/workflows/build-dappnode.yaml
+++ b/.github/workflows/build-dappnode.yaml
@@ -89,15 +89,25 @@ jobs:
       - name: Setup variables
         id: setup
         run: |
+          # Set current_version based on branch type:
+          # - For PRs: <current_version>-pr.<PR_number>
+          # - For 'master' branch: <master_version>-latest
+          # - For 'release/*' branches: <release_version>-latest
+          # - For other branches: exit with error
           current_version=$(./scripts/get-current-version.sh docker)
           if [ -z "${{ github.event.pull_request.number }}" ]; then
+            echo "Invoked manually"
             declare base_branch=${{ steps.vars.outputs.GITHUB_REF_NAME }}
-            if [ "${base_branch}" == "master" ]; then
-              echo "current_version=latest" >> $GITHUB_OUTPUT
+            if [[ "${base_branch}" == "master" ]]; then
+              echo "current_version=${{ vars.BRANCH_MASTER_RELEASE_NAME }}-latest" >> $GITHUB_OUTPUT
+            elif [[ "${base_branch}" =~ ^"release" ]]; then
+              echo "current_version=${{ vars.BRANCH_RELEASE_RELEASE_NAME }}-latest" >> $GITHUB_OUTPUT
             else
-              echo "current_version=${base_branch/release\//}-latest" >> $GITHUB_OUTPUT
+              echo "Cannot generate a dAppNode package from branch ${base_branch}"
+              exit 1
             fi
           else
+            echo "Invoked from a pull request"
             echo "current_version=${current_version}-pr.${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
           fi
 
