Create a deployment flag

diff --git a/.github/workflows/deploy-nodes.yaml b/.github/workflows/deploy-nodes.yaml
--- a/.github/workflows/deploy-nodes.yaml
+++ b/.github/workflows/deploy-nodes.yaml
@@ -55,16 +55,13 @@ jobs:
       - name: "Restart deployment for cluster ${{ steps.vars.outputs.HOPRD_CLUSTER_NAME }}"
         run: |
           echo "Starting deployment restart for cluster ${{ steps.vars.outputs.HOPRD_CLUSTER_NAME }}"
-          for node in `kubectl get deployment -n core-team -l hoprds.hoprnet.org/cluster=${{ steps.vars.outputs.HOPRD_CLUSTER_NAME }} -o jsonpath='{.items[*].metadata.name}'`; do
-            echo "Deploying $node"; 
-            if ! kubectl rollout restart deployments -n core-team $node; then
-              echo "Failed to restart deployment"
-              exit 1
-            fi
-            if ! kubectl rollout status deployments -n core-team $node --timeout=600s; then
-              echo "Deployment did not complete within the timeout period"
-              exit 1
-            fi
-          done
+          if ! kubectl rollout restart deployments -n core-team -l hoprds.hoprnet.org/cluster=${{ steps.vars.outputs.HOPRD_CLUSTER_NAME }}; then
+            echo "Failed to restart deployment"
+            exit 1
+          fi
+          if ! kubectl rollout status deployments -n core-team -l hoprds.hoprnet.org/cluster=${{ steps.vars.outputs.HOPRD_CLUSTER_NAME }} --timeout=600s; then
+            echo "Deployment did not complete within the timeout period"
+            exit 1
+          fi
           echo "Deployment completed successfully"
         timeout-minutes: 11
