More coderabbit suggestions

diff --git a/.github/workflows/deploy-nodes.yaml b/.github/workflows/deploy-nodes.yaml
--- a/.github/workflows/deploy-nodes.yaml
+++ b/.github/workflows/deploy-nodes.yaml
@@ -7,6 +7,13 @@ name: Deploy Nodes
 on:
   repository_dispatch:
     types: [deploy_nodes]
+  workflow_dispatch:
+    inputs:
+      hoprd_cluster_name:
+        description: 'Name of the hoprd cluster to deploy'
+        required: true
+        type: string
+        default: "core-node"
 
 concurrency:
   group: deploy-nodes
@@ -38,8 +45,29 @@ jobs:
           location: europe-west3
           project_id: hopr-staging
 
-      - name: "Restart deployment for cluster ${{ github.event.client_payload.hoprd_cluster_name }}"
+      - name: Set environment variables
+        id: vars
         run: |
-          kubectl rollout restart deployments -n core-team -l hoprds.hoprnet.org/cluster=${{ github.event.client_payload.hoprd_cluster_name }}
-          kubectl rollout status  deployments -n core-team -l hoprds.hoprnet.org/cluster=${{ github.event.client_payload.hoprd_cluster_name }} --timeout=600s
+          if [ -z "${{ inputs.hoprd_cluster_name }}" ]; then
+            echo "The workflow is triggered from other pipeline"
+            {
+              echo "HOPRD_CLUSTER_NAME=${{ github.event.client_payload.hoprd_cluster_name }}"
+            } >> $GITHUB_OUTPUT
+          else
+            echo "The workflow is triggered manually"
+            {
+              echo "HOPRD_CLUSTER_NAME=${{ inputs.hoprd_cluster_name }}"
+            } >> $GITHUB_OUTPUT
+          fi
+
+      - name: "Restart deployment for cluster ${{ steps.vars.outputs.HOPRD_CLUSTER_NAME }}"
+        run: |
+          if ! kubectl rollout restart deployments -n core-team -l hoprds.hoprnet.org/cluster=${{ steps.vars.outputs.HOPRD_CLUSTER_NAME }}; then
+            echo "Failed to restart deployment"
+            exit 1
+          fi
+          if ! kubectl rollout status deployments -n core-team -l hoprds.hoprnet.org/cluster=${{ steps.vars.outputs.HOPRD_CLUSTER_NAME }} --timeout=600s; then
+            echo "Deployment did not complete within the timeout period"
+            exit 1
+          fi
         timeout-minutes: 11
