Coderabbit suggestions

diff --git a/.github/workflows/k8s.yaml b/.github/workflows/k8s.yaml
--- a/.github/workflows/k8s.yaml
+++ b/.github/workflows/k8s.yaml
@@ -42,8 +42,11 @@ jobs:
           # Identify parameters depending on branch
           if [[ "${base_branch}" =~ ^"release" ]]; then
             network=${{ vars.HOPRD_NETWORK_MAINNET }}
-          else
+          elif [[ "${base_branch}" =~ ^"master" ]]; then
             network=${{ vars.HOPRD_NETWORK_TESTNET }}
+          else
+            echo "Error: Deployment not supported for branch ${base_branch}"
+            exit 1
           fi
           cd ./hoprnet-ci
           pip install -r ./scripts/requirements.txt
