Restoring version

diff --git a/.github/workflows/merge.yml b/.github/workflows/merge.yml
--- a/.github/workflows/merge.yml
+++ b/.github/workflows/merge.yml
@@ -3,8 +3,8 @@ name: Merge
 on:
   pull_request:
     types:
-      # - closed
-      - synchronize
+      - closed
+      #- synchronize
 
 concurrency:
   group: merge
@@ -18,110 +18,110 @@ env:
   MATRIX_ACCESS_TOKEN: ${{ secrets.MATRIX_ACCESS_TOKEN }}
 
 jobs:
-  # cleanup-actions:
-  #   name: Cleanup Actions
-  #   runs-on: ubuntu-2-core
-  #   steps:
-  #     - name: Checkout hoprnet repository
-  #       uses: actions/checkout@v3
-  #     - name: Cleanup
-  #       run: |
-  #         gh extension install actions/gh-actions-cache
+  cleanup-actions:
+    name: Cleanup Actions
+    runs-on: ubuntu-2-core
+    steps:
+      - name: Checkout hoprnet repository
+        uses: actions/checkout@v3
+      - name: Cleanup
+        run: |
+          gh extension install actions/gh-actions-cache
 
-  #         REPO=${{ github.repository }}
-  #         BRANCH="refs/pull/${{ github.event.pull_request.number }}/merge"
+          REPO=${{ github.repository }}
+          BRANCH="refs/pull/${{ github.event.pull_request.number }}/merge"
 
-  #         echo "Fetching list of cache key"
-  #         cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )
+          echo "Fetching list of cache key"
+          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )
 
-  #         ## Setting this to not fail the workflow while deleting cache keys.
-  #         set +e
-  #         echo "Deleting caches..."
-  #         for cacheKey in $cacheKeysForPR
-  #         do
-  #           gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
-  #         done
-  #         echo "Done"
-  #       env:
-  #         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          ## Setting this to not fail the workflow while deleting cache keys.
+          set +e
+          echo "Deleting caches..."
+          for cacheKey in $cacheKeysForPR
+          do
+            gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
+          done
+          echo "Done"
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-  # tag:
-  #   name: Tag images
-  #   runs-on: ubuntu-2-core
-  #   if: github.event.pull_request.merged == true && (github.event.pull_request.base.ref == 'master' || contains(github.event.pull_request.base.ref,'release/'))
-  #   steps:
-  #     - name: Checkout hoprnet repository
-  #       uses: actions/checkout@v3
-  #       with:
-  #         fetch-depth: 0
+  tag:
+    name: Tag images
+    runs-on: ubuntu-2-core
+    if: github.event.pull_request.merged == true && (github.event.pull_request.base.ref == 'master' || contains(github.event.pull_request.base.ref,'release/'))
+    steps:
+      - name: Checkout hoprnet repository
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-  #     - name: Check PR changes
-  #       id: check_pr_changeset
-  #       run: |
-  #         git fetch -u --progress origin pull/${{ github.event.pull_request.number }}/head:${{ github.event.pull_request.head.ref }}
-  #         ./scripts/check-pr.sh --base-branch ${{ github.event.pull_request.base.sha }} --head-branch ${{ github.event.pull_request.head.sha }}
-  #         cat check_pr.log >> $GITHUB_OUTPUT
-  #         cat check_pr.log
-  #         declare base_branch=${{ github.event.pull_request.base.ref }}
-  #         if [ "${base_branch}" == "master" ]; then
-  #           echo "DOCKER_STABLE_TAG=latest"  >> $GITHUB_ENV
-  #         else
-  #           echo "DOCKER_STABLE_TAG=${base_branch/release\//}" >> $GITHUB_ENV
-  #         fi
-  #         ./scripts/bump-version.sh ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.number }}
-  #         echo "DOCKER_PR_TAG=$(./scripts/get-package-version.sh | sed 's/+/-/' )" >> $GITHUB_ENV
-  #         echo "DOCKER_REGISTRY=europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images" >> $GITHUB_ENV
+      - name: Check PR changes
+        id: check_pr_changeset
+        run: |
+          git fetch -u --progress origin pull/${{ github.event.pull_request.number }}/head:${{ github.event.pull_request.head.ref }}
+          ./scripts/check-pr.sh --base-branch ${{ github.event.pull_request.base.sha }} --head-branch ${{ github.event.pull_request.head.sha }}
+          cat check_pr.log >> $GITHUB_OUTPUT
+          cat check_pr.log
+          declare base_branch=${{ github.event.pull_request.base.ref }}
+          if [ "${base_branch}" == "master" ]; then
+            echo "DOCKER_STABLE_TAG=latest"  >> $GITHUB_ENV
+          else
+            echo "DOCKER_STABLE_TAG=${base_branch/release\//}" >> $GITHUB_ENV
+          fi
+          ./scripts/bump-version.sh ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.number }}
+          echo "DOCKER_PR_TAG=$(./scripts/get-package-version.sh | sed 's/+/-/' )" >> $GITHUB_ENV
+          echo "DOCKER_REGISTRY=europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images" >> $GITHUB_ENV
 
-  #     - name: Set up Google Cloud Credentials
-  #       id: auth
-  #       uses: google-github-actions/auth@v1
-  #       with:
-  #         token_format: "access_token"
-  #         credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
+      - name: Set up Google Cloud Credentials
+        id: auth
+        uses: google-github-actions/auth@v1
+        with:
+          token_format: "access_token"
+          credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
 
-  #     - name: Login Google Container Registry
-  #       uses: docker/login-action@v2
-  #       with:
-  #         registry: europe-west3-docker.pkg.dev
-  #         username: oauth2accesstoken
-  #         password: ${{ steps.auth.outputs.access_token }}
+      - name: Login Google Container Registry
+        uses: docker/login-action@v2
+        with:
+          registry: europe-west3-docker.pkg.dev
+          username: oauth2accesstoken
+          password: ${{ steps.auth.outputs.access_token }}
 
-  #     - name: Docker Tag Toolchain
-  #       if: steps.check_pr_changeset.outputs.build_toolchain
-  #       run: |
-  #         docker pull ${{ env.DOCKER_REGISTRY }}/hopr-toolchain:${{ env.DOCKER_PR_TAG }}
-  #         docker tag ${{ env.DOCKER_REGISTRY }}/hopr-toolchain:${{ env.DOCKER_PR_TAG }} ${{ env.DOCKER_REGISTRY }}/hopr-toolchain:${{ env.DOCKER_STABLE_TAG }}
-  #         docker push ${{ env.DOCKER_REGISTRY }}/hopr-toolchain:${{ env.DOCKER_STABLE_TAG }}
-  #     - name: Docker Tag Hopli
-  #       if: steps.check_pr_changeset.outputs.build_toolchain || steps.check_pr_changeset.outputs.build_hopli
-  #       run: |
-  #         docker pull ${{ env.DOCKER_REGISTRY }}/hopli:${{ env.DOCKER_PR_TAG }}
-  #         docker tag ${{ env.DOCKER_REGISTRY }}/hopli:${{ env.DOCKER_PR_TAG }} ${{ env.DOCKER_REGISTRY }}/hopli:${{ env.DOCKER_STABLE_TAG }}
-  #         docker push ${{ env.DOCKER_REGISTRY }}/hopli:${{ env.DOCKER_STABLE_TAG }}
-  #     - name: Docker Tag Hoprd
-  #       if: steps.check_pr_changeset.outputs.build_toolchain || steps.check_pr_changeset.outputs.build_hoprd
-  #       run: |
-  #         docker pull ${{ env.DOCKER_REGISTRY }}/hoprd:${{ env.DOCKER_PR_TAG }}
-  #         docker tag ${{ env.DOCKER_REGISTRY }}/hoprd:${{ env.DOCKER_PR_TAG }} ${{ env.DOCKER_REGISTRY }}/hoprd:${{ env.DOCKER_STABLE_TAG }}
-  #         docker push ${{ env.DOCKER_REGISTRY }}/hoprd:${{ env.DOCKER_STABLE_TAG }}
-  #     - name: Docker Tag Anvil
-  #       if: steps.check_pr_changeset.outputs.build_toolchain || steps.check_pr_changeset.outputs.build_anvil
-  #       run: |
-  #         docker pull ${{ env.DOCKER_REGISTRY }}/hopr-anvil:${{ env.DOCKER_PR_TAG }}
-  #         docker tag ${{ env.DOCKER_REGISTRY }}/hopr-anvil:${{ env.DOCKER_PR_TAG }} ${{ env.DOCKER_REGISTRY }}/hopr-anvil:${{ env.DOCKER_STABLE_TAG }}
-  #         docker push ${{ env.DOCKER_REGISTRY }}/hopr-anvil:${{ env.DOCKER_STABLE_TAG }}
-  #     - name: Docker Tag Pluto
-  #       run: |
-  #         docker pull ${{ env.DOCKER_REGISTRY }}/hopr-pluto:${{ env.DOCKER_PR_TAG }}
-  #         docker tag ${{ env.DOCKER_REGISTRY }}/hopr-pluto:${{ env.DOCKER_PR_TAG }} ${{ env.DOCKER_REGISTRY }}/hopr-pluto:${{ env.DOCKER_STABLE_TAG }}
-  #         docker push ${{ env.DOCKER_REGISTRY }}/hopr-pluto:${{ env.DOCKER_STABLE_TAG }}
+      - name: Docker Tag Toolchain
+        if: steps.check_pr_changeset.outputs.build_toolchain
+        run: |
+          docker pull ${{ env.DOCKER_REGISTRY }}/hopr-toolchain:${{ env.DOCKER_PR_TAG }}
+          docker tag ${{ env.DOCKER_REGISTRY }}/hopr-toolchain:${{ env.DOCKER_PR_TAG }} ${{ env.DOCKER_REGISTRY }}/hopr-toolchain:${{ env.DOCKER_STABLE_TAG }}
+          docker push ${{ env.DOCKER_REGISTRY }}/hopr-toolchain:${{ env.DOCKER_STABLE_TAG }}
+      - name: Docker Tag Hopli
+        if: steps.check_pr_changeset.outputs.build_toolchain || steps.check_pr_changeset.outputs.build_hopli
+        run: |
+          docker pull ${{ env.DOCKER_REGISTRY }}/hopli:${{ env.DOCKER_PR_TAG }}
+          docker tag ${{ env.DOCKER_REGISTRY }}/hopli:${{ env.DOCKER_PR_TAG }} ${{ env.DOCKER_REGISTRY }}/hopli:${{ env.DOCKER_STABLE_TAG }}
+          docker push ${{ env.DOCKER_REGISTRY }}/hopli:${{ env.DOCKER_STABLE_TAG }}
+      - name: Docker Tag Hoprd
+        if: steps.check_pr_changeset.outputs.build_toolchain || steps.check_pr_changeset.outputs.build_hoprd
+        run: |
+          docker pull ${{ env.DOCKER_REGISTRY }}/hoprd:${{ env.DOCKER_PR_TAG }}
+          docker tag ${{ env.DOCKER_REGISTRY }}/hoprd:${{ env.DOCKER_PR_TAG }} ${{ env.DOCKER_REGISTRY }}/hoprd:${{ env.DOCKER_STABLE_TAG }}
+          docker push ${{ env.DOCKER_REGISTRY }}/hoprd:${{ env.DOCKER_STABLE_TAG }}
+      - name: Docker Tag Anvil
+        if: steps.check_pr_changeset.outputs.build_toolchain || steps.check_pr_changeset.outputs.build_anvil
+        run: |
+          docker pull ${{ env.DOCKER_REGISTRY }}/hopr-anvil:${{ env.DOCKER_PR_TAG }}
+          docker tag ${{ env.DOCKER_REGISTRY }}/hopr-anvil:${{ env.DOCKER_PR_TAG }} ${{ env.DOCKER_REGISTRY }}/hopr-anvil:${{ env.DOCKER_STABLE_TAG }}
+          docker push ${{ env.DOCKER_REGISTRY }}/hopr-anvil:${{ env.DOCKER_STABLE_TAG }}
+      - name: Docker Tag Pluto
+        run: |
+          docker pull ${{ env.DOCKER_REGISTRY }}/hopr-pluto:${{ env.DOCKER_PR_TAG }}
+          docker tag ${{ env.DOCKER_REGISTRY }}/hopr-pluto:${{ env.DOCKER_PR_TAG }} ${{ env.DOCKER_REGISTRY }}/hopr-pluto:${{ env.DOCKER_STABLE_TAG }}
+          docker push ${{ env.DOCKER_REGISTRY }}/hopr-pluto:${{ env.DOCKER_STABLE_TAG }}
 
   deploy_prn_nodes:
     name: Deploy PRN nodes
     runs-on: ubuntu-2-core
-    # if: needs.tag.result == 'success'
-    # needs:
-    #   - tag
+    if: needs.tag.result == 'success'
+    needs:
+      - tag
     steps:
       - name: Checkout hoprnet repository
         uses: actions/checkout@v3
@@ -194,63 +194,63 @@ jobs:
           ./scripts/notify-matrix-github-workflow-failure.sh "${MATRIX_ROOM}" "${{ github.repository }}" \
             "${{ github.workflow }}" "${{ github.run_id }}"
 
-  # deploy_natted_nodes:
-  #   name: Deploy Natted nodes
-  #   runs-on: ubuntu-2-core
-  #   if: needs.tag.result == 'success'
-  #   needs:
-  #     - tag
-  #   steps:
-  #     - name: Checkout hoprnet repository
-  #       uses: actions/checkout@v3
+  deploy_natted_nodes:
+    name: Deploy Natted nodes
+    runs-on: ubuntu-2-core
+    if: needs.tag.result == 'success'
+    needs:
+      - tag
+    steps:
+      - name: Checkout hoprnet repository
+        uses: actions/checkout@v3
 
-  #     - name: "Restart deployments"
-  #       run: |
-  #         prBase="${{ github.event.pull_request.base.ref }}"
-  #         # Identify the network to deploy nodes
-  #         network=$(jq -r "to_entries[] | select(.value.git_ref | test(\"${prBase/*\/}\")).value.network" packages/hoprd/releases.json | sed 's/_/-/')
-  #         # In case the base PR is pointing to an unknown branch/release, we deploy to the default network "rotsee"
-  #         if [ -z $network ]; then 
-  #           echo "No network selected"
-  #           exit 1;
-  #         fi
-  #         echo "[INFO] Restarting deployments on ${network} from pr-${{ github.event.pull_request.number }}"
-  #         # Get list of deployments to restart
-  #         export deployments=($(kubectl get deployments -n ${network} -l hoprds.hoprnet.org/cluster=hoprd-${network} -o jsonpath="{.items[*].metadata.name}"))
-  #         for deployment in "${deployments[@]}"; do
-  #           echo "[INFO] Restarting hoprd node ${deployments}"
-  #           kubectl rollout restart deployments -n ${network} $deployment;
-  #         done
+      - name: "Restart deployments"
+        run: |
+          prBase="${{ github.event.pull_request.base.ref }}"
+          # Identify the network to deploy nodes
+          network=$(jq -r "to_entries[] | select(.value.git_ref | test(\"${prBase/*\/}\")).value.network" packages/hoprd/releases.json | sed 's/_/-/')
+          # In case the base PR is pointing to an unknown branch/release, we deploy to the default network "rotsee"
+          if [ -z $network ]; then 
+            echo "No network selected"
+            exit 1;
+          fi
+          echo "[INFO] Restarting deployments on ${network} from pr-${{ github.event.pull_request.number }}"
+          # Get list of deployments to restart
+          export deployments=($(kubectl get deployments -n ${network} -l hoprds.hoprnet.org/cluster=hoprd-${network} -o jsonpath="{.items[*].metadata.name}"))
+          for deployment in "${deployments[@]}"; do
+            echo "[INFO] Restarting hoprd node ${deployments}"
+            kubectl rollout restart deployments -n ${network} $deployment;
+          done
 
-  # cleanup-docker:
-  #   name: Cleanup Docker
-  #   runs-on: ubuntu-2-core
-  #   needs:
-  #     - tag
-  #   steps:
-  #     - name: Checkout hoprnet repository
-  #       uses: actions/checkout@v3
+  cleanup-docker:
+    name: Cleanup Docker
+    runs-on: ubuntu-2-core
+    needs:
+      - tag
+    steps:
+      - name: Checkout hoprnet repository
+        uses: actions/checkout@v3
 
-  #     - name: Set up Google Cloud Credentials
-  #       id: auth
-  #       uses: google-github-actions/auth@v1
-  #       with:
-  #         token_format: "access_token"
-  #         credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
+      - name: Set up Google Cloud Credentials
+        id: auth
+        uses: google-github-actions/auth@v1
+        with:
+          token_format: "access_token"
+          credentials_json: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
 
-  #     - name: Set up Google Cloud SDK
-  #       uses: google-github-actions/setup-gcloud@v1
-  #       with:
-  #         project_id: ${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}
-  #         install_components: beta
+      - name: Set up Google Cloud SDK
+        uses: google-github-actions/setup-gcloud@v1
+        with:
+          project_id: ${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}
+          install_components: beta
 
-  #     - name: Cleanup Docker images
-  #       run: |
-  #         images=('hopli' 'hoprd' 'hopr-anvil' 'hopr-pluto' 'hopr-toolchain' 'hoprd')
-  #         for image in "${images[@]}"; do
-  #           image_tags=$(gcloud artifacts docker images list --include-tags europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images/${image} --format="json" 2> /dev/null | jq -r --arg date "$date"  '.[] | select(.tags | length > 0) | select(.tags | contains("-pr.${{ github.event.pull_request.number }}")).version')
-  #           for image_tag in $image_tags; do
-  #             gcloud artifacts docker images delete --quiet --delete-tags --async europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images/${image}@${image_tag}
-  #           done
-  #         done
+      - name: Cleanup Docker images
+        run: |
+          images=('hopli' 'hoprd' 'hopr-anvil' 'hopr-pluto' 'hopr-toolchain' 'hoprd')
+          for image in "${images[@]}"; do
+            image_tags=$(gcloud artifacts docker images list --include-tags europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images/${image} --format="json" 2> /dev/null | jq -r --arg date "$date"  '.[] | select(.tags | length > 0) | select(.tags | contains("-pr.${{ github.event.pull_request.number }}")).version')
+            for image_tag in $image_tags; do
+              gcloud artifacts docker images delete --quiet --delete-tags --async europe-west3-docker.pkg.dev/${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}/docker-images/${image}@${image_tag}
+            done
+          done
 
