feat: Add binary signatures and multiple os package improvements (#7297)
Co-authored-by: coderabbitai[bot] <136622811+coderabbitai[bot]@users.noreply.github.com>
Co-authored-by: Tino Breddin <tolbrino@users.noreply.github.com>

diff --git a/.github/workflows/package.yaml b/.github/workflows/package.yaml
--- a/.github/workflows/package.yaml
+++ b/.github/workflows/package.yaml
@@ -13,12 +13,18 @@ on:
       target:
         required: true
         type: string
+      packager:
+        required: true
+        type: string
+      extension:
+        required: true
+        type: string
       workflow_run_id:
         required: true
         type: string
 
 concurrency:
-  group: ${{ inputs.branch }}-package-${{ inputs.target }}
+  group: ${{ inputs.branch }}-package-${{ inputs.target }}-${{ inputs.packager }}
   cancel-in-progress: true
 
 jobs:
@@ -36,10 +42,12 @@ jobs:
         id: gcp
         uses: hoprnet/hopr-workflows/actions/setup-gcp@12c56020e16036982e6cc529848edeedfc705865 # master
         with:
-          google-credentials: ${{ secrets.GCP_SA_TERRAFORM_JSON }}
+          google-credentials: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
           login-artifact-registry: 'false'
           install-sdk: 'true'
+
       - name: Download artifacts from parent workflow run
+        id: download
         run: |
           set -euo pipefail  # Enable strict error handling
           mkdir -p ./dist/bin
@@ -60,6 +68,7 @@ jobs:
           # Download and unzip hoprd artifact
           curl -s -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$hoprd_url" -o hoprd-${{ inputs.target }}.zip || { echo "Failed to download hoprd artifact"; exit 1; }
           unzip -o hoprd-${{ inputs.target }}.zip -d ./dist/bin || { echo "Failed to unzip hoprd artifact"; exit 1; }
+          mv ./dist/bin/hoprd-${{ inputs.target }} ./dist/bin/hoprd || { echo "Failed to rename hoprd binary"; exit 1; }
 
           # Extract hopli artifact URL
           hopli_url=$(jq -r '.artifacts[] | select(.name == "hopli-${{ inputs.target }}").archive_download_url' artifacts.json)
@@ -71,6 +80,13 @@ jobs:
           # Download and unzip hopli artifact
           curl -s -L -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$hopli_url" -o hopli-${{ inputs.target }}.zip || { echo "Failed to download hopli artifact"; exit 1; }
           unzip -o hopli-${{ inputs.target }}.zip -d ./dist/bin || { echo "Failed to unzip hopli artifact"; exit 1; }
+          mv ./dist/bin/hopli-${{ inputs.target }} ./dist/bin/hopli || { echo "Failed to rename hopli binary"; exit 1; }
+
+          current_version=$(./scripts/get-current-version.sh)
+          architecture=${{ inputs.target }}
+          # Remove suffix from architecture
+          architecture=${architecture%-linux}
+          echo "package_file_name=hoprd_${current_version}_${architecture}" | tee -a $GITHUB_OUTPUT
 
       - name: Install Nix
         uses: cachix/install-nix-action@17fe5fb4a23ad6cbbe47d6b3f359611ad276644c # v31
@@ -85,56 +101,27 @@ jobs:
         env:
           USER: runner
 
-      - name: Package binaries
-        run: nix develop -c just package ${{ inputs.target }}
+      - name: Package
+        run: nix develop -c just package ${{ inputs.packager }} ${{ inputs.target }}
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Test Package debian
+      - name: Test Package
         if: vars.TEST_OS_PACKAGE_ENABLED == 'true'
         continue-on-error: true
         run: |
           echo "${{ secrets.TEST_OS_PACKAGE_HOPR_IDENTITY_FILE }}" | base64 -d > ${{ github.workspace }}/deploy/nfpm/hopr.id
           chmod 600 ${{ github.workspace }}/deploy/nfpm/hopr.id
-          nix develop -c just test-package deb ${{ inputs.target }}
+          nix develop -c just test-package ${{ inputs.packager }} ${{ inputs.target }}
         env:
           HOPRD_PASSWORD: ${{ secrets.TEST_OS_PACKAGE_HOPRD_PASSWORD }}
           HOPRD_SAFE_ADDRESS: ${{ secrets.TEST_OS_PACKAGE_HOPRD_SAFE_ADDRESS }}
           HOPRD_MODULE_ADDRESS: ${{ secrets.TEST_OS_PACKAGE_HOPRD_MODULE_ADDRESS }}
           HOPRD_PROVIDER: ${{ secrets.TEST_OS_PACKAGE_HOPRD_PROVIDER }}
+          GCP_PROJECT: ${{ secrets.GOOGLE_HOPRASSOCIATION_PROJECT }}
 
-      - name: Test Package centos
-        if: vars.TEST_OS_PACKAGE_ENABLED == 'true'
-        continue-on-error: true
-        run: nix develop -c just test-package rpm ${{ inputs.target }}
-        env:
-          HOPRD_PASSWORD: ${{ secrets.TEST_OS_PACKAGE_HOPRD_PASSWORD }}
-          HOPRD_SAFE_ADDRESS: ${{ secrets.TEST_OS_PACKAGE_HOPRD_SAFE_ADDRESS }}
-          HOPRD_MODULE_ADDRESS: ${{ secrets.TEST_OS_PACKAGE_HOPRD_MODULE_ADDRESS }}
-          HOPRD_PROVIDER: ${{ secrets.TEST_OS_PACKAGE_HOPRD_PROVIDER }}
-
-      - name: Test Package archlinux
-        if: vars.TEST_OS_PACKAGE_ENABLED == 'true'
-        continue-on-error: true
-        run: nix develop -c just test-package archlinux ${{ inputs.target }}
-        env:
-          HOPRD_PASSWORD: ${{ secrets.TEST_OS_PACKAGE_HOPRD_PASSWORD }}
-          HOPRD_SAFE_ADDRESS: ${{ secrets.TEST_OS_PACKAGE_HOPRD_SAFE_ADDRESS }}
-          HOPRD_MODULE_ADDRESS: ${{ secrets.TEST_OS_PACKAGE_HOPRD_MODULE_ADDRESS }}
-          HOPRD_PROVIDER: ${{ secrets.TEST_OS_PACKAGE_HOPRD_PROVIDER }}
-
-      - name: Upload debian packaged artifact
+      - name: Upload packaged artifact
         uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
         with:
-          name: hoprd-${{ inputs.target }}.deb
-          path: ${{ github.workspace }}/dist/packages/hoprd-${{ inputs.target }}.deb
-
-      - name: Upload centos packaged artifact
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
-        with:
-          name: hoprd-${{ inputs.target }}.rpm
-          path: ${{ github.workspace }}/dist/packages/hoprd-${{ inputs.target }}.rpm
-
-      - name: Upload archlinux packaged artifact
-        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
-        with:
-          name: hoprd-${{ inputs.target }}.pkg.tar.zst
-          path: ${{ github.workspace }}/dist/packages/hoprd-${{ inputs.target }}.archlinux
+          name: ${{ steps.download.outputs.package_file_name }}.${{ inputs.extension }}
+          path: ${{ github.workspace }}/dist/packages/hoprd-${{ inputs.target }}.${{ inputs.packager }}
